### PR TITLE
updates install.sh

### PR DESCRIPTION
**Pull request by mathieu-aubin**
Adds more options to install.sh, mainly:

- _Bash_ completion directory _pseudo-detection_
- Possibility to use custom _bash_ completion directory
- Get completion file from a [_https://git.io_](https://git.io/minify-completion.bash) url -> always up-to-date
- Enables static linking option using `CGO_ENABLED=0` when `--static` is passed as first argument
- Strip binary after compilation

### CODE REVIEW

**Comment by tdewolff** [comment]
Thanks for the PR. Changes looks good, but I have two point:

- I don't think it's good to use an updated version of the bach completion. If someone downloads a version of `minify` they should use the bash completion that comes with that version. Newer versions may show discrepancy between the binary and the bash completion.
- `minify` doesn't use CGO and neither does its dependencies (AFAIK), so I don't think the CGO stuff is needed and the binary should be static automatically.

Otherwise, I like the automatic bash completion installation.

One worry I have when creating this install script is that it doesn't recognize the version of the library. For example, if you download the sources from v2.7.2 it will print as its version `develop@fea781f` for example, and not `v2.7.2`. The compiled binaries do print the version correctly. Any way you think we can fix that?

**Comment by mathieu-aubin** [comment]
Hey man
as far as CGO is concerned, i noticed that if there's already a defined exported variable to 1, it will not 

compile statically. `CGO_ENABLED=1 go build` will in fact link dynamically so the reason why i thought about adding it was to allow static linking without much changes, quickly and conveniently, for the environments where it's defined.

As for the completion url, it could be used as some sort of a updater at some point, within the program or even, the binary could contains its own completion and auto-extract it auto or upon request. Oh well.. methods priority could also be swapped, using file first and if not present, try url..

For the version... `git describe --tags` should return the lastest tag of the current checked-out branch.

**Comment by mathieu-aubin** [comment]
it seems you could get your answers by checking the process wich is used when you run `goreleaser release --debug`

adding the debug shows it tries some different stuff to get a representative (true) tag for the {{.Version}}. Replicating it in bash would not be too hard from there

**Comment by tdewolff** [comment]
With a commit hook we could update a file everytime we push a commit, but I think that would create some trouble with merges or whatever. It creates a lot of clutter wrt changes/diffs. I've set the `git describe --tags` output to `Version` for Goreleaser and for the `install.sh`.

I really don't want it to check anything by URL. Not only might it create a security risk, it also puts the bash completion and the library out of phase wrt to versions. It should only ever install the bash completion that comes with the source once, and never use an older or newer version. An auto-updater is not on the roadmap, almost all target OSs have package systems and I don't want to interfere.

The `CGO_ENABLED` should always be put to `0` I think. This library should always be compiled statically.

The bash completion directories that it tries to install the script to, where did you obtain this list? Is this a common way of installing completion scripts? Do other big libraries use the same?

**Pull request closed without merging**
