### PR TITLE
Node.JS bindings Worker threads segfault reproduction

### PR DESCRIPTION
**Pull request by perrin4869**
I added a minimal test that reproduces the segfault issue. Unfortunately using the global stack didn't fix the issue
I'm afraid that maybe the go runtime might have internal resources that cannot be cleaned, in which case this issue could maybe not ever be solved? Really hope not...
Now, I also noticed if the module is loaded in both the main thread and in the worker thread, the application does not segfault and the tests pass beautifully (i.e, instead of `const { config, string } = await import('@tdewolff/minify')`, do `import { config, string } from '@tdewolff/minify'`)

### CODE REVIEW

**Comment by tdewolff** [comment]
Thanks for the test case, it segfaults here too. I'll look into finding the root cause

**Comment by tdewolff** [comment]
Been trying to use https://www.npmjs.com/package/segfault-handler but it requires the `require` syntax and when changing it to the `import` syntax it doesn't "self-register". I've tried a couple of things to get it to work but with little luck...

**Comment by tdewolff** [comment]
Update, running the following script of CommonJS also generates the segmentation fault:

```js
const { Worker, isMainThread, workerData, parentPort } = require('node:worker_threads');

if (isMainThread) {
    let input = "<html><span style=\"color:#ff0000;\">A  phrase</span>";
    const worker = new Worker(new URL('file:///home/taco/go/src/github.com/tdewolff/minify/bindings/js/test/worker.js'), {
        workerData: input,
    });

    let expected = "<html><span style=color:red>A phrase</span>";
    let output = new Promise((resolve, reject) => {
        worker.on('message', resolve);
        worker.on('error', reject);
        worker.on('exit', (code) => {
            if (code !== 0)
            reject(new Error(`Worker stopped with exit code ${code}`));
        });
    })
} else {
    const { string } = require('@tdewolff/minify');
    string("text/html", workerData);
}
```

However, using the segfault-handler as mentioned above, the segmentation fault is not caught! :-S

**Comment by tdewolff** [comment]
I've found it, I had to add a clean up hook and call `os.Exit(0)` explicitly!

**Comment by perrin4869** [comment]
Thanks!!! This is working perfectly here: https://github.com/dotcore64/rollup-plugin-tdewolff-minify/pull/7
Maybe it would be a good idea to merge this instead of closing to keep the regression test?

**Comment by perrin4869** [comment]
Ah just need to update https://github.com/tdewolff/minify/blob/2eed2f639ec2e7fafff016105c0b46e341e28bdb/bindings/js/package.json#L3 to `2.12.0` to deploy to `npm` :)

**Comment by tdewolff** [comment]
That ought to happen automatically in the Makefile that we invoke from the workflow. Just now I'm running the build script: https://github.com/tdewolff/minify/actions/runs/2645307256

**Comment by perrin4869** [comment]
Dammit this is actually not a good solution, `os.Exit` terminates the node process:

https://github.com/dotcore64/rollup-plugin-tdewolff-minify/runs/7272307346?check_suite_focus=true

**Pull request merged**
