### PR TITLE
Automate prebuilds publishing

### PR DESCRIPTION
**Pull request by perrin4869**
An attempt to automate the release process.
Also, I try to run the `nodejs` workflow only if the `golang` workflow passed
Edit: `workflow_on` doesn't seem to wanna work... maybe it only works after it is merged?

### CODE REVIEW

**Comment by tdewolff** [comment]
Nice thanks for the PR. Not sure why I never thought about it, but it makes sense to publish directly from a GitHub action. I'll need to set the login information for PyPI in this repo though.

Anyways, looking at this, I'm not sure if we need the upload/download, why don't we call `npm publish` directly in the `Install` step?

**Comment by perrin4869** [comment]
Ah yeah you'll need to setup a secret with the npm token in it, i was forgetting!
I won't be home until tomorrow in the evening though 😅
There's a setup to publish to npm: https://github.com/dotcore64/i18next-fetch-backend/blob/master/.github/workflows/release.yml

The deploy job runs after the test job finishes on all 3 platforms, that way it can pull all 3 binaries!
The install step is inside the test job 😀

**Comment by perrin4869** [comment]
Ah, i was forgetting, it's probably best to build the binaries using node 14, since that's the lowest version supported. i think that running a binary built by node 18 in node 14 is not strictly supported

**Comment by tdewolff** [comment]
Ah yes, I was forgetting the matrix job needs to finish first. All looks good to me! I suppose we can merge?

**Comment by perrin4869** [comment]
Sorry, it was still incomplete! Let me send a PR with the remaining changes :)
Also, not sure if this will work until you actually push a tag

**Comment by perrin4869** [comment]
Ah sorry I see you updated this! Thanks :)

**Comment by perrin4869** [comment]
I think we do actually need the `if: startsWith(github.ref, 'refs/tags/v')` part, otherwise it will try to deploy even when the version hasn't changed

**Comment by tdewolff** [comment]
I thought the if statement wasn't necessary since we only ever run the workflow when a new version gets published. I.e., the version tag is set and different from the previous, should be enough I suppose? Let me know if you think otherwise ;-)

**Comment by perrin4869** [comment]
Ah right! Yeah I thought it was still running for pull requests too!

**Pull request merged**
