### PR TITLE
html: Add `KeepInlineSvg` option

### PR DESCRIPTION
**Pull request by satotake**
I admit that I need the option for only a few edge cases finally, but it may be worth for some people until implementation of svg minification will have been done.

### CODE REVIEW

**Comment by tdewolff** [comment]
Thanks for the PR. I think if you have a problem you could just not attach the SVG minifier, unless you use the CLI surely. Is that the case? I think it would be better then to have a switch solely in the CLI that excludes the SVG minifier.

Better yet would be to fix the SVG minifier. What problem are you experiencing? Even though it is incomplete it should give valid results.

**Comment by satotake** [comment]
Thanks for your help, @tdewolff 

As you pointed out,
> unless you use the CLI surely. Is that the case?

I am using `minify` CLI because I am not familiar with golang itself so much.

> What problem are you experiencing?

This might be too much description but let me explain it

I have some index.html including inline svgs like

```html
<svg>
  <g id="parent">
     <g id="child1"> </g>
     <g id="child2"> </g>
  </g>
</svg>
```
Originally,  these elements are manipulated with javascript in browsers based on their id.
With `minify`, the empty container tags are collapsed and raise unexptected js errors.
Of course, cases like mine will be rare and your design to collapse empty tags is reasonable in terms of saving html size. I completely agree with it.

>  I think it would be better then to have a switch solely in the CLI that excludes the SVG minifier.

This spec also meets my needs. 
I rewrote this PR. Could you review it again?

**Comment by tdewolff** [comment]
Hm, I see the problem you state, and perhaps the SVG minifier should not remove tags or groups, in the same sense it does not remove HTML tags either. In your case however, the groups would still exist but be collapsed, since they have an attribute set. I think the best way would be to keep group tags so that access patterns from JS or CSS would still apply properly.

**Comment by tdewolff** [comment]
Is the problem that JS cannot access void tags and handles them differently than empty tags? What error is raised and what JS do you use to access it?

**Comment by satotake** [comment]
I am very sorry for presenting a bad example.
I updated (deleting whitespaces within child group tags).
With the updated example,  `minify` actually delete group tags even if they have attributes.

Input: index.html
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>title</title>
    </head>
    <body>
        <svg>
          <g id="parent">
             <g id="child1"></g>
             <g id="child2"></g>
          </g>
        </svg>
    </body>
    <script type="text/javascript">
        var rect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
        rect.setAttribute('width', '15')
        rect.setAttribute('height', '15')
        document.querySelector('#child1').appendChild(rect);
    </script>
</html>

```

`minify -o index.min.html index.html`

```html
<!doctype html><html lang=en><meta charset=utf-8><title>title</title><svg><g id="parent"></g></svg><script>var rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('width','15')
rect.setAttribute('height','15')
document.querySelector('#child1').appendChild(rect);</script>
```
raise 
```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at index.min.html:3
```

**Comment by satotake** [comment]
> perhaps the SVG minifier should not remove tags or groups, in the same sense it does not remove HTML tags either.

It sounds safer for me.
It may be better to have an option for keeping tags in SVG (as HTML minifier: safe) or not (as `minify` has been: compression-efficient)

**Comment by satotake** [comment]
I also made #197 in response to 

```
Hm, I see the problem you state, and perhaps the SVG minifier should not remove tags or groups,
in the same sense it does not remove HTML tags either.
```

Whichever ( #190 or #197 ) is fine for me!

**Comment by tdewolff** [comment]
I think #197 or a variation on it would be better, so I'll close this PR.

**Pull request closed without merging**
