### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by niiigoo**
I wanted to use minify within a docker based pipeline. Therefore, i haved added a Dockerfile.

### CODE REVIEW

**Comment by tdewolff** [comment]
Excellent, thank you!

**Comment by niiigoo** [comment]
No problem. It would be perfect if you create a repository on [hub.docker.com](https://hub.docker.com). Currently, the docker image is available in my [repo](https://hub.docker.com/r/niiigoo/minify), but it will only be updated when i merge the changes from this git repo into my fork. Shall i create an issue instead of continuing the conversation here?

**Comment by tdewolff** [comment]
Great! I've added it at https://hub.docker.com/r/tdewolff/minify, can you check if that works fine? (for some reason the readme doesn't get updated...)

**Comment by niiigoo** [comment]
It seems, that the connection GitHub is not configured. Do you have added a build configuration? There you can add this repo and a rule to build the image automatically. The readme will be updated after the first build

**Comment by niiigoo** [comment]
For now i recommend following rules:
image

**Comment by tdewolff** [comment]
Thanks, looks like it's building now!

**Comment by niiigoo** [comment]
Perfect, i have removed it from my hub.docker account and i have deleted my fork

**Pull request merged**
