### PR TITLE
Use switch-case in some minifiers

### PR DESCRIPTION
**Pull request by bogem**
Improve the readability of code

### CODE REVIEW

**Comment by tdewolff** [comment]
I believe the switch statement was slower. I remember testing it back then, but maybe it has improved in time though. Besides, I think the readability improvement is minimal...

**Comment by bogem** [comment]
I don't think it's slower, but someone should check it.
Yes, the readability is increased not much, but it's logical to use switch-case in these conditions.

**Comment by tdewolff** [comment]
This is really hard to test. I've been running a couple of benchmarks but they seem to be pretty equivalent (as expected, I only expect differences of a few percent anyways). I _think_ the switch case is ever so slightly slower, but this might be biased. However running the following benchmark does give a more tangible result:

```
BenchmarkIf-8             200000              6844 ns/op
BenchmarkSwitch-8         200000              7342 ns/op

# if I comment the count = [6]int{} at the start of each benchmark
BenchmarkIf-8             200000              6804 ns/op
BenchmarkSwitch-8         300000              4161 ns/op
```

using

```go
type Hash uint32

const (
	A Hash = 0x3206
	B Hash = 0x23c0f
	C Hash = 0x101
	D Hash = 0x15609
	E Hash = 0x1b40a
	F Hash = 0x320e
)

var hashes = [6]Hash{A, B, C, D, E, F}
var count = [6]int{}

var buf []Hash

func init() {
	rand.Seed(time.Now().UTC().UnixNano())

	buf = make([]Hash, 1000)
	for i := range buf {
		buf[i] = hashes[rand.Intn(len(hashes))]
	}
}

func BenchmarkIf(b *testing.B) {
	count = [6]int{}
	for i := 0; i < b.N; i++ {
		for _, hash := range buf {
			if hash == A {
				count[0]++
			} else if hash == B {
				count[1]++
			} else if hash == C {
				count[2]++
			} else if hash == D {
				count[3]++
			} else if hash == E {
				count[4]++
			} else if hash == F {
				count[5]++
			}
		}
	}
}

func BenchmarkSwitch(b *testing.B) {
	count = [6]int{}
	for i := 0; i < b.N; i++ {
		for _, hash := range buf {
			switch hash {
			case A:
				count[0]++
			case B:
				count[1]++
			case C:
				count[2]++
			case D:
				count[3]++
			case E:
				count[4]++
			case F:
				count[5]++
			}
		}
	}
}
```

**Comment by tdewolff** [comment]
Not so surprisingly, switch is faster with a `default` case instead of testing for `F`:

```go
BenchmarkIf-8                     200000              6963 ns/op
BenchmarkSwitch-8                 200000              7646 ns/op
BenchmarkSwitchDefault-8          200000              7104 ns/op
```

I can't really say if the `switch` statement degrades performance, if it does at all it's not by much. However, I don't see the benefit of this PR; it has (very) little gain and possible performance loss...

**Comment by tdewolff** [comment]
Hmm, when I use a struct element that has to be tested, benchmark is different:

```
BenchmarkIf-8                     200000              7019 ns/op
BenchmarkSwitch-8                 200000              6816 ns/op
BenchmarkSwitchDefault-8          200000              6419 ns/op
```

using

```go

type HashS struct {
	s string
	h Hash
}

var hashes = [6]HashS{{"a", A}, {"b", B}, {"c", C}, {"d", D}, {"e", E}, {"a", F}}
var buf []HashS

// ...

// if hash.h == A {
// vs
// switch hash.h {
```

**Comment by tdewolff** [comment]
Well, the `BenchmarkSwitchDefault` one is the functional equivalent of using an `else` at the end of the `if / else if` sequence, so we can't compare that to `BenchmarkIf`.

Looking at the ASM output they are both equal (using only `A`, `B` and `C` and leaving the rest out for simplicity):

```asm
0x0000 00000 (main_test.go:36)  TEXT    "".BenchmarkIf(SB), $0-8
0x0000 00000 (main_test.go:36)  NOP
0x0000 00000 (main_test.go:36)  NOP
0x0000 00000 (main_test.go:36)  FUNCDATA        $0, gclocals·87d20ce1b58390b294df80b886db78bf(SB)
0x0000 00000 (main_test.go:36)  FUNCDATA        $1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
0x0000 00000 (main_test.go:37)  MOVQ    $0, "".count(SB)
0x000b 00011 (main_test.go:37)  MOVQ    $0, "".count+8(SB)
0x0016 00022 (main_test.go:37)  MOVQ    $0, "".count+16(SB)
0x0021 00033 (main_test.go:38)  MOVQ    "".b+8(FP), AX
0x0026 00038 (main_test.go:38)  MOVQ    $0, CX
0x0028 00040 (main_test.go:38)  MOVQ    184(AX), DX
0x002f 00047 (main_test.go:38)  CMPQ    CX, DX
0x0032 00050 (main_test.go:38)  JGE     $0, 128
0x0034 00052 (main_test.go:39)  MOVQ    "".buf(SB), DX
0x003b 00059 (main_test.go:39)  MOVQ    "".buf+8(SB), BX
0x0042 00066 (main_test.go:38)  MOVQ    $0, SI
0x0044 00068 (main_test.go:39)  CMPQ    SI, BX
0x0047 00071 (main_test.go:39)  JGE     $0, 113
0x0049 00073 (main_test.go:39)  MOVL    16(DX), DI
0x004c 00076 (main_test.go:40)  CMPL    DI, $12806
0x0052 00082 (main_test.go:40)  JNE     129
0x0054 00084 (main_test.go:41)  MOVQ    "".count(SB), DI
0x005b 00091 (main_test.go:41)  INCQ    DI
0x005e 00094 (main_test.go:41)  MOVQ    DI, "".count(SB)
0x0065 00101 (main_test.go:39)  ADDQ    $24, DX
0x0069 00105 (main_test.go:39)  INCQ    SI
0x006c 00108 (main_test.go:39)  CMPQ    SI, BX
0x006f 00111 (main_test.go:39)  JLT     $0, 73
0x0071 00113 (main_test.go:38)  INCQ    CX
0x0074 00116 (main_test.go:38)  MOVQ    184(AX), DX
0x007b 00123 (main_test.go:38)  CMPQ    CX, DX
0x007e 00126 (main_test.go:38)  JLT     $0, 52
0x0080 00128 (main_test.go:49)  RET
0x0081 00129 (main_test.go:42)  CMPL    DI, $146447
0x0087 00135 (main_test.go:42)  JNE     156
0x0089 00137 (main_test.go:43)  MOVQ    "".count+8(SB), DI
0x0090 00144 (main_test.go:43)  INCQ    DI
0x0093 00147 (main_test.go:43)  MOVQ    DI, "".count+8(SB)
0x009a 00154 (main_test.go:39)  JMP     101
0x009c 00156 (main_test.go:44)  CMPL    DI, $257
0x00a2 00162 (main_test.go:44)  JNE     101
0x00a4 00164 (main_test.go:45)  MOVQ    "".count+16(SB), DI
0x00ab 00171 (main_test.go:45)  INCQ    DI
0x00ae 00174 (main_test.go:45)  MOVQ    DI, "".count+16(SB)
0x00b5 00181 (main_test.go:39)  JMP     101

0x0000 00000 (main_test.go:51)  TEXT    "".BenchmarkSwitch(SB), $0-8
0x0000 00000 (main_test.go:51)  NOP
0x0000 00000 (main_test.go:51)  NOP
0x0000 00000 (main_test.go:51)  FUNCDATA        $0, gclocals·87d20ce1b58390b294df80b886db78bf(SB)
0x0000 00000 (main_test.go:51)  FUNCDATA        $1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
0x0000 00000 (main_test.go:52)  MOVQ    $0, "".count(SB)
0x000b 00011 (main_test.go:52)  MOVQ    $0, "".count+8(SB)
0x0016 00022 (main_test.go:52)  MOVQ    $0, "".count+16(SB)
0x0021 00033 (main_test.go:53)  MOVQ    "".b+8(FP), AX
0x0026 00038 (main_test.go:53)  MOVQ    $0, CX
0x0028 00040 (main_test.go:53)  MOVQ    184(AX), DX
0x002f 00047 (main_test.go:53)  CMPQ    CX, DX
0x0032 00050 (main_test.go:53)  JGE     $0, 128
0x0034 00052 (main_test.go:54)  MOVQ    "".buf(SB), DX
0x003b 00059 (main_test.go:54)  MOVQ    "".buf+8(SB), BX
0x0042 00066 (main_test.go:53)  MOVQ    $0, SI
0x0044 00068 (main_test.go:54)  CMPQ    SI, BX
0x0047 00071 (main_test.go:54)  JGE     $0, 113
0x0049 00073 (main_test.go:54)  MOVL    16(DX), DI
0x004c 00076 (main_test.go:60)  CMPL    DI, $257
0x0052 00082 (main_test.go:60)  JNE     129
0x0054 00084 (main_test.go:61)  MOVQ    "".count+16(SB), DI
0x005b 00091 (main_test.go:61)  INCQ    DI
0x005e 00094 (main_test.go:61)  MOVQ    DI, "".count+16(SB)
0x0065 00101 (main_test.go:54)  ADDQ    $24, DX
0x0069 00105 (main_test.go:54)  INCQ    SI
0x006c 00108 (main_test.go:54)  CMPQ    SI, BX
0x006f 00111 (main_test.go:54)  JLT     $0, 73
0x0071 00113 (main_test.go:53)  INCQ    CX
0x0074 00116 (main_test.go:53)  MOVQ    184(AX), DX
0x007b 00123 (main_test.go:53)  CMPQ    CX, DX
0x007e 00126 (main_test.go:53)  JLT     $0, 52
0x0080 00128 (main_test.go:65)  RET
0x0081 00129 (main_test.go:56)  CMPL    DI, $12806
0x0087 00135 (main_test.go:56)  JNE     156
0x0089 00137 (main_test.go:57)  MOVQ    "".count(SB), DI
0x0090 00144 (main_test.go:57)  INCQ    DI
0x0093 00147 (main_test.go:57)  MOVQ    DI, "".count(SB)
0x009a 00154 (main_test.go:54)  JMP     101
0x009c 00156 (main_test.go:58)  CMPL    DI, $146447
0x00a2 00162 (main_test.go:58)  JNE     101
0x00a4 00164 (main_test.go:59)  MOVQ    "".count+8(SB), DI
0x00ab 00171 (main_test.go:59)  INCQ    DI
0x00ae 00174 (main_test.go:59)  MOVQ    DI, "".count+8(SB)
0x00b5 00181 (main_test.go:54)  JMP     101
```

The only difference is the ordering of local variables, thus different access offsets for `MOVQ`. Probably, the `switch` version doesn't have to add the offset as much as the `if` version.

**Comment by tdewolff** [comment]
Alright, I figured it out. The `switch` case tests for `C` first, then `A` and then `B`. The if-statement naturally keeps its test order.

I thought that `switch had to keep its order, but apparently it may swap it around. This is actually undesirable. I'd like full control over the order of testing though, because the optimal order of testing is determined from a test set of data.

Self note: the HTML minifier could benefit from better ordering (using `if-else`).

**Comment by bogem** [comment]
Wow, thanks for this detailed explanation. I didn't know what `switch` has different order.
If the check order is important for you and you don't want to merge it, no problem.

**Pull request closed without merging**
