### PR TITLE
add KeepCDATA option in xml minify

### PR DESCRIPTION
**Pull request by lpha**
Sometimes Keep CDATA will be more safety.

### CODE REVIEW

**Comment by tdewolff** [comment]
In which cases will it be safer? The minifier should only remove CDATA in safe cases, so hopefully an option is not necessary

**Comment by lpha** [comment]
```
        <Extensions>
          <Extension type="Extra">
            <CTA>
              <![CDATA[>>]]>
            </CTA>
          </Extension>
        </Extensions>
```

In this case above , the minify will delete the CDATA and the string will be 
```
<Extensions><Extension type="Extra"><CTA>
>></CTA></Extension></Extensions>
```

I knew you are right so i closed the PR but we can not prove all the xml parser works perfect so we expect to use CDATA to ensure their xml parser will not be crashed when some unexpected string appears.

**Comment by tdewolff** [comment]
That should be fine, since `>>` is perfectly valid as text in XML and doesn't need to be escaped. See https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-CharData and note that only `&` and `<` are prohibited. Thank you for the effort though! And if you run into trouble, please let me know!

**Comment by rodrigorodriguescosta** [comment]
I had to insert CDATA because it was hard to scape `", &, ', <, >` why not use that function to keep CDATA?  

you said `The minifier should only remove CDATA in safe cases` what are the safe cases? it has removed CDATA with the cases above

**Pull request closed without merging**
