### PR TITLE
Add r and d flags

### PR DESCRIPTION
**Pull request by variadico**
Add flags to minify files in a directory, and optionally traverse the directory recursively.

### CODE REVIEW

**Comment by tdewolff** [comment]
I will review this ASAP when I'm less occupied!

**Comment by variadico** [comment]
Refactored. Back to you.

**Comment by variadico** [comment]
Do you get notified when I push an update to my fork or do I have to keep posting a comment here? :smile:

**Comment by tdewolff** [comment]
No I don't get notified of pushes by mail, weirdly...

**Comment by variadico** [comment]
Cheers! :beers:

**Comment by tdewolff** [comment]
Hey, I did some refactoring on your code: 73a9e2df3169b7c84afb925b0cf0074d2847e54e
What do you think?

**Comment by variadico** [comment]
Hey, sorry about the late reply! Got hit with a bunch of work recently.

Overall, changes seem mostly cosmetic. So, as long as everything works, cool! :smile:

**Pull request merged**
